export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCT = "DELETE_ALL_PRODUCT";
export const CHECK_PRODUCT = "CHECK_PRODUCT";
export const CHECK_ALL_PRODUCT = "CHECK_ALL_PRODUCT";
export const VISIBILITY_FILTER = " VISIBILITY_FILTER";
